# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Demo_ui(object):
    def setupUi(self, Demo_ui):
        Demo_ui.setObjectName("Demo_ui")
        Demo_ui.resize(400, 300)
        self.update_demo_btn = QtWidgets.QDialogButtonBox(Demo_ui)
        self.update_demo_btn.setGeometry(QtCore.QRect(40, 250, 341, 32))
        self.update_demo_btn.setOrientation(QtCore.Qt.Horizontal)
        self.update_demo_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.update_demo_btn.setObjectName("update_demo_btn")
        self.post_demo = QtWidgets.QPlainTextEdit(Demo_ui)
        self.post_demo.setGeometry(QtCore.QRect(30, 20, 351, 221))
        self.post_demo.setOverwriteMode(True)
        self.post_demo.setObjectName("post_demo")

        self.retranslateUi(Demo_ui)
        self.update_demo_btn.accepted.connect(Demo_ui.accept) # type: ignore
        self.update_demo_btn.rejected.connect(Demo_ui.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Demo_ui)

    def retranslateUi(self, Demo_ui):
        _translate = QtCore.QCoreApplication.translate
        Demo_ui.setWindowTitle(_translate("Demo_ui", "Dialog"))
        self.post_demo.setPlainText(_translate("Demo_ui", "#不需先付押金才能排隊看房\n"
"…………………………………………………\n"
"\n"
"{title}\n"
"\n"
"\n"
"租金：{rent}\n"
"類型：{kind}\n"
"樓層：{floor}\n"
"寵物：不可\n"
"電費：台水電\n"
"車位：已含租金（平面車位)\n"
"備註：\n"
"⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯"))
