# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Share_post.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shared_post(object):
    def setupUi(self, shared_post):
        shared_post.setObjectName("shared_post")
        shared_post.resize(429, 532)
        shared_post.setStyleSheet("")
        self.label = QtWidgets.QLabel(shared_post)
        self.label.setGeometry(QtCore.QRect(0, 0, 631, 171))
        self.label.setStyleSheet("background-color:rgb(231,121,24);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(shared_post)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 371, 461))
        self.label_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(shared_post)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 271, 71))
        self.label_3.setStyleSheet("background-color: rgb(231,121,24);\n"
"image: url(:/icon/icon/logo.png);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(shared_post)
        self.label_5.setGeometry(QtCore.QRect(40, 470, 21, 21))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/icon/icon/person.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(shared_post)
        self.label_6.setGeometry(QtCore.QRect(40, 500, 21, 21))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/icon/icon/phone.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.poser_name = QtWidgets.QLabel(shared_post)
        self.poser_name.setGeometry(QtCore.QRect(70, 470, 141, 31))
        self.poser_name.setStyleSheet("font: 75 10pt \"微軟正黑體\";")
        self.poser_name.setObjectName("poser_name")
        self.label_7 = QtWidgets.QLabel(shared_post)
        self.label_7.setGeometry(QtCore.QRect(-50, 170, 551, 381))
        self.label_7.setStyleSheet("background-color:rgb(255, 231, 207);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.poster_phton = QtWidgets.QLabel(shared_post)
        self.poster_phton.setGeometry(QtCore.QRect(70, 500, 141, 31))
        self.poster_phton.setStyleSheet("font: 75 10pt \"微軟正黑體\";")
        self.poster_phton.setObjectName("poster_phton")
        self.post_title = QtWidgets.QLabel(shared_post)
        self.post_title.setGeometry(QtCore.QRect(30, 270, 371, 61))
        self.post_title.setStyleSheet("font: 14pt \"標楷體\";\n"
"font-color:;\n"
"color: rgb(231,121,24);")
        self.post_title.setWordWrap(True)
        self.post_title.setObjectName("post_title")
        self.house_kind = QtWidgets.QLabel(shared_post)
        self.house_kind.setGeometry(QtCore.QRect(30, 230, 101, 31))
        self.house_kind.setStyleSheet("font: 12pt \"標楷體\";\n"
"background-color: rgb(231,121,24);\n"
"color: rgb(255, 255, 255);")
        self.house_kind.setObjectName("house_kind")
        self.address = QtWidgets.QLabel(shared_post)
        self.address.setGeometry(QtCore.QRect(40, 330, 281, 21))
        self.address.setStyleSheet("font: 12pt \"標楷體\";\n"
"color:rgb(166, 166, 166);")
        self.address.setObjectName("address")
        self.detail_info = QtWidgets.QLabel(shared_post)
        self.detail_info.setGeometry(QtCore.QRect(40, 360, 161, 101))
        self.detail_info.setStyleSheet("font: 10pt \"標楷體\";")
        self.detail_info.setText("")
        self.detail_info.setWordWrap(True)
        self.detail_info.setObjectName("detail_info")
        self.qrcode = QtWidgets.QLabel(shared_post)
        self.qrcode.setGeometry(QtCore.QRect(260, 400, 141, 131))
        self.qrcode.setStyleSheet("")
        self.qrcode.setText("")
        self.qrcode.setObjectName("qrcode")
        self.rent_cost = QtWidgets.QLabel(shared_post)
        self.rent_cost.setGeometry(QtCore.QRect(240, 350, 161, 41))
        self.rent_cost.setStyleSheet("font: 18pt \"標楷體\";\n"
"color: rgb(255, 140, 250);")
        self.rent_cost.setObjectName("rent_cost")
        self.post_img = QtWidgets.QLabel(shared_post)
        self.post_img.setGeometry(QtCore.QRect(30, 70, 371, 201))
        self.post_img.setStyleSheet("background-color: rgb(115, 115, 255);")
        self.post_img.setText("")
        self.post_img.setObjectName("post_img")
        self.label_7.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.poser_name.raise_()
        self.poster_phton.raise_()
        self.post_title.raise_()
        self.address.raise_()
        self.detail_info.raise_()
        self.qrcode.raise_()
        self.rent_cost.raise_()
        self.post_img.raise_()
        self.house_kind.raise_()

        self.retranslateUi(shared_post)
        QtCore.QMetaObject.connectSlotsByName(shared_post)

    def retranslateUi(self, shared_post):
        _translate = QtCore.QCoreApplication.translate
        shared_post.setWindowTitle(_translate("shared_post", "Form"))
        self.poser_name.setText(_translate("shared_post", "陳小姐"))
        self.poster_phton.setText(_translate("shared_post", "0900-000-000"))
        self.post_title.setText(_translate("shared_post", "台中美宅"))
        self.house_kind.setText(_translate("shared_post", "社區"))
        self.address.setText(_translate("shared_post", "台中市x區xx路段"))
        self.rent_cost.setText(_translate("shared_post", "5000元/月"))
